/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package devso2;

/**
 *
 * @author xchel
 */
public class interfaz extends javax.swing.JFrame {

    /**
     * Creates new form interfaz
     */
    public interfaz() {
        initComponents();
        pnlDesarrollo.setVisible(false);
        pnlVentas.setVisible(false);//movimientos reportes
        pnlMovimientos.setVisible(false);
        pnlReportes.setVisible(false);
        pnlIngresos.setVisible(false);
        pnlEgresos.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuVentasDisponibles = new javax.swing.JPopupMenu();
        btnVender = new javax.swing.JMenuItem();
        menuVentasNoDisponibles = new javax.swing.JPopupMenu();
        btnGenerarEstadoContrato = new javax.swing.JMenuItem();
        btnInfoVenta = new javax.swing.JMenuItem();
        btnPagos = new javax.swing.JMenuItem();
        btnDevaluacion = new javax.swing.JMenuItem();
        btnAgregar = new javax.swing.JMenuItem();
        pnlViewMain = new javax.swing.JPanel();
        pnlView = new javax.swing.JPanel();
        pnlMenuLateral = new javax.swing.JPanel();
        pnlMenuLateral1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btnDesarrollo = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        btnVenta = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        btnMovimientos = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        RbtnReportes = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        pnlOpcionesInterfaz = new javax.swing.JPanel();
        pnlVentas = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableVentas = new javax.swing.JTable();
        pnlDesarrollo = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        PnlMenuSuperior1 = new javax.swing.JPanel();
        btnEditProject = new javax.swing.JButton();
        btnAddPlanPago = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        pnlMovimientos = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        PnlMenuSuperior = new javax.swing.JPanel();
        btnIngresos = new javax.swing.JButton();
        btnEgresos = new javax.swing.JButton();
        btnMovCaja = new javax.swing.JButton();
        btnRegistro = new javax.swing.JButton();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        pnlIngresos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rdFacturaYes = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        rdFacturaNo = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cbCategoriaIngresos = new javax.swing.JComboBox<>();
        cbCuentaIngresos = new javax.swing.JComboBox<>();
        txtIVA = new javax.swing.JTextField();
        txtConcepto = new javax.swing.JTextField();
        dtFecha = new com.toedter.calendar.JDateChooser();
        txtNumFactura = new javax.swing.JTextField();
        txtMontoTotal = new javax.swing.JTextField();
        txtMontoNoIVA = new javax.swing.JTextField();
        txtMontoIVA = new javax.swing.JTextField();
        txtConcepto1 = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        pnlEgresos = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        rdFacturaYes1 = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        rdFacturaNo1 = new javax.swing.JRadioButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        cbCategoriaEgresos = new javax.swing.JComboBox<>();
        cbCuentaEgresos = new javax.swing.JComboBox<>();
        txtIVA1 = new javax.swing.JTextField();
        txtConcepto2 = new javax.swing.JTextField();
        dtFecha1 = new com.toedter.calendar.JDateChooser();
        txtNumFactura1 = new javax.swing.JTextField();
        txtMontoTotal1 = new javax.swing.JTextField();
        txtMontoNoIVA1 = new javax.swing.JTextField();
        txtMontoIVA1 = new javax.swing.JTextField();
        txtConcepto3 = new javax.swing.JTextField();
        btnGuardar2 = new javax.swing.JButton();
        pnlMovCaja = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        cbCategoriaEgresos1 = new javax.swing.JComboBox<>();
        cbCuentaEgresos1 = new javax.swing.JComboBox<>();
        dtFecha2 = new com.toedter.calendar.JDateChooser();
        txtConcepto5 = new javax.swing.JTextField();
        btnGuardar3 = new javax.swing.JButton();
        cbCuentaEgresos2 = new javax.swing.JComboBox<>();
        jLabel63 = new javax.swing.JLabel();
        pnlReportes = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        tlbrNuevoDesarrollo = new javax.swing.JMenuItem();
        tlbrCargarDesarrollo = new javax.swing.JMenuItem();
        tlbrAdministración = new javax.swing.JMenuItem();

        btnVender.setText("Realizar venta");
        btnVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderActionPerformed(evt);
            }
        });
        menuVentasDisponibles.add(btnVender);

        btnGenerarEstadoContrato.setText("jMenuItem1");
        menuVentasNoDisponibles.add(btnGenerarEstadoContrato);

        btnInfoVenta.setText("jMenuItem1");
        menuVentasNoDisponibles.add(btnInfoVenta);

        btnPagos.setText("jMenuItem1");
        menuVentasNoDisponibles.add(btnPagos);

        btnDevaluacion.setText("jMenuItem1");
        menuVentasNoDisponibles.add(btnDevaluacion);

        btnAgregar.setText("jMenuItem1");
        menuVentasNoDisponibles.add(btnAgregar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setFont(new java.awt.Font("Malgun Gothic", 0, 14)); // NOI18N

        pnlView.setBackground(new java.awt.Color(0, 0, 0));

        pnlMenuLateral.setBackground(new java.awt.Color(47, 51, 66));

        pnlMenuLateral1.setBackground(new java.awt.Color(47, 51, 66));

        jLabel12.setText("jLabel12");

        btnDesarrollo.setBackground(new java.awt.Color(123, 163, 186));
        btnDesarrollo.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        btnDesarrollo.setForeground(new java.awt.Color(255, 255, 255));
        btnDesarrollo.setText("Desarrollo");
        btnDesarrollo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDesarrollo.setBorderPainted(false);
        btnDesarrollo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesarrolloActionPerformed(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        jLabel32.setText("Desarrollo");

        btnVenta.setBackground(new java.awt.Color(123, 163, 186));
        btnVenta.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        btnVenta.setForeground(new java.awt.Color(255, 255, 255));
        btnVenta.setText("Venta");
        btnVenta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVenta.setBorderPainted(false);
        btnVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentaActionPerformed(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        jLabel33.setText("Venta");

        btnMovimientos.setBackground(new java.awt.Color(123, 163, 186));
        btnMovimientos.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        btnMovimientos.setForeground(new java.awt.Color(255, 255, 255));
        btnMovimientos.setText("Movimientos");
        btnMovimientos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMovimientos.setBorderPainted(false);
        btnMovimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovimientosActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        jLabel34.setText("Movimientos");

        RbtnReportes.setBackground(new java.awt.Color(123, 163, 186));
        RbtnReportes.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        RbtnReportes.setForeground(new java.awt.Color(255, 255, 255));
        RbtnReportes.setText("Reportes");
        RbtnReportes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        RbtnReportes.setBorderPainted(false);
        RbtnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbtnReportesActionPerformed(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        jLabel35.setText("Reportes");

        javax.swing.GroupLayout pnlMenuLateral1Layout = new javax.swing.GroupLayout(pnlMenuLateral1);
        pnlMenuLateral1.setLayout(pnlMenuLateral1Layout);
        pnlMenuLateral1Layout.setHorizontalGroup(
            pnlMenuLateral1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDesarrollo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnMovimientos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(RbtnReportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlMenuLateral1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMenuLateral1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlMenuLateral1Layout.createSequentialGroup()
                        .addGroup(pnlMenuLateral1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        pnlMenuLateral1Layout.setVerticalGroup(
            pnlMenuLateral1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLateral1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDesarrollo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMovimientos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel34)
                .addGap(3, 3, 3)
                .addComponent(RbtnReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel35)
                .addContainerGap(192, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlMenuLateralLayout = new javax.swing.GroupLayout(pnlMenuLateral);
        pnlMenuLateral.setLayout(pnlMenuLateralLayout);
        pnlMenuLateralLayout.setHorizontalGroup(
            pnlMenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
            .addGroup(pnlMenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlMenuLateral1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMenuLateralLayout.setVerticalGroup(
            pnlMenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 985, Short.MAX_VALUE)
            .addGroup(pnlMenuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlMenuLateral1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlOpcionesInterfaz.setBackground(new java.awt.Color(47, 51, 66));

        pnlVentas.setBackground(new java.awt.Color(47, 51, 66));

        jPanel5.setBackground(new java.awt.Color(47, 51, 66));

        tableVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Cliente", "Apartado", "# Unidad", "Etapa", "Modelo", "Tablaje", "# m2", "PV M2", "Precio venta", "Anticipo", "Monto anticipado", "Fecha anticipo", "Financiamiento", "# Mensualidades", "Monto mensualidades", "Monto de cada mensualidad", "Fecha de inicio financiamiento", "Fecha final de financiamiento", "Porcentaje saldo", "Monto de saldo", "Fecha de saldo", "Fecha venta", "Fecha ultimo pago"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tableVentasMouseReleased(evt);
            }
        });
        jScrollPane3.setViewportView(tableVentas);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1056, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1056, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 858, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 858, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlVentasLayout = new javax.swing.GroupLayout(pnlVentas);
        pnlVentas.setLayout(pnlVentasLayout);
        pnlVentasLayout.setHorizontalGroup(
            pnlVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlVentasLayout.setVerticalGroup(
            pnlVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVentasLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnlDesarrollo.setBackground(new java.awt.Color(47, 51, 66));

        jPanel4.setBackground(new java.awt.Color(47, 51, 66));

        PnlMenuSuperior1.setBackground(new java.awt.Color(47, 51, 66));

        btnEditProject.setBackground(new java.awt.Color(123, 163, 186));
        btnEditProject.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        btnEditProject.setForeground(new java.awt.Color(255, 255, 255));
        btnEditProject.setText("Editar proyecto");
        btnEditProject.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEditProject.setBorderPainted(false);
        btnEditProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditProjectActionPerformed(evt);
            }
        });

        btnAddPlanPago.setBackground(new java.awt.Color(123, 163, 186));
        btnAddPlanPago.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        btnAddPlanPago.setForeground(new java.awt.Color(255, 255, 255));
        btnAddPlanPago.setText("Agregar plan de pago");
        btnAddPlanPago.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAddPlanPago.setBorderPainted(false);

        jLabel29.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        jLabel29.setText("Editar proyecto");

        jLabel30.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        jLabel30.setText("Agregar plan de pago");

        javax.swing.GroupLayout PnlMenuSuperior1Layout = new javax.swing.GroupLayout(PnlMenuSuperior1);
        PnlMenuSuperior1.setLayout(PnlMenuSuperior1Layout);
        PnlMenuSuperior1Layout.setHorizontalGroup(
            PnlMenuSuperior1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlMenuSuperior1Layout.createSequentialGroup()
                .addGroup(PnlMenuSuperior1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditProject, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlMenuSuperior1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(btnAddPlanPago, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(822, Short.MAX_VALUE))
        );
        PnlMenuSuperior1Layout.setVerticalGroup(
            PnlMenuSuperior1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlMenuSuperior1Layout.createSequentialGroup()
                .addGroup(PnlMenuSuperior1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnAddPlanPago, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                    .addComponent(btnEditProject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(PnlMenuSuperior1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(47, 51, 66));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 852, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlMenuSuperior1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(PnlMenuSuperior1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlDesarrolloLayout = new javax.swing.GroupLayout(pnlDesarrollo);
        pnlDesarrollo.setLayout(pnlDesarrolloLayout);
        pnlDesarrolloLayout.setHorizontalGroup(
            pnlDesarrolloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlDesarrolloLayout.setVerticalGroup(
            pnlDesarrolloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlMovimientos.setBackground(new java.awt.Color(47, 51, 66));
        pnlMovimientos.setPreferredSize(new java.awt.Dimension(1056, 973));

        jPanel6.setBackground(new java.awt.Color(47, 51, 66));

        PnlMenuSuperior.setBackground(new java.awt.Color(47, 51, 66));

        btnIngresos.setBackground(new java.awt.Color(123, 163, 186));
        btnIngresos.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        btnIngresos.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresos.setText("Ingresos");
        btnIngresos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnIngresos.setBorderPainted(false);
        btnIngresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresosActionPerformed(evt);
            }
        });

        btnEgresos.setBackground(new java.awt.Color(123, 163, 186));
        btnEgresos.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        btnEgresos.setForeground(new java.awt.Color(255, 255, 255));
        btnEgresos.setText("Egresos");
        btnEgresos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEgresos.setBorderPainted(false);
        btnEgresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEgresosActionPerformed(evt);
            }
        });

        btnMovCaja.setBackground(new java.awt.Color(123, 163, 186));
        btnMovCaja.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        btnMovCaja.setForeground(new java.awt.Color(255, 255, 255));
        btnMovCaja.setText("Movimiento de caja");
        btnMovCaja.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMovCaja.setBorderPainted(false);
        btnMovCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMovCajaActionPerformed(evt);
            }
        });

        btnRegistro.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        btnRegistro.setText("Ver registro");
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });

        jLabel42.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setText("Ingresos");

        jLabel43.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("Egresos");

        jLabel44.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("Movimientos de caja");

        jLabel24.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        jLabel24.setText("Ver registros");

        javax.swing.GroupLayout PnlMenuSuperiorLayout = new javax.swing.GroupLayout(PnlMenuSuperior);
        PnlMenuSuperior.setLayout(PnlMenuSuperiorLayout);
        PnlMenuSuperiorLayout.setHorizontalGroup(
            PnlMenuSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlMenuSuperiorLayout.createSequentialGroup()
                .addGroup(PnlMenuSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnIngresos, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(jLabel42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlMenuSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEgresos, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(jLabel43, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnlMenuSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMovCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(PnlMenuSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnlMenuSuperiorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 575, Short.MAX_VALUE)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlMenuSuperiorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0))))
        );
        PnlMenuSuperiorLayout.setVerticalGroup(
            PnlMenuSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlMenuSuperiorLayout.createSequentialGroup()
                .addGroup(PnlMenuSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnMovCaja, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEgresos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIngresos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PnlMenuSuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(jLabel43)
                    .addComponent(jLabel44)
                    .addComponent(jLabel24))
                .addContainerGap())
        );

        pnlIngresos.setBackground(new java.awt.Color(47, 51, 66));

        jLabel1.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Fecha");

        jLabel2.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Categoría");

        jLabel3.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Concepto");

        jLabel4.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Cuenta");

        jLabel5.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Forma de pago");

        jLabel6.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("IVA");

        rdFacturaYes.setBackground(new java.awt.Color(204, 204, 204));
        rdFacturaYes.setForeground(new java.awt.Color(0, 0, 0));
        rdFacturaYes.setText("Sí");
        rdFacturaYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdFacturaYesActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("Factura");

        rdFacturaNo.setBackground(new java.awt.Color(204, 204, 204));
        rdFacturaNo.setForeground(new java.awt.Color(0, 0, 0));
        rdFacturaNo.setText("No");

        jLabel8.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("Num. factura");

        jLabel9.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setText("Monto total");

        jLabel10.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel10.setText("Monto sin IVA");

        jLabel11.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel11.setText("Monto IVA");

        cbCategoriaIngresos.setBackground(new java.awt.Color(204, 204, 204));
        cbCategoriaIngresos.setEditable(true);
        cbCategoriaIngresos.setForeground(new java.awt.Color(0, 0, 0));
        cbCategoriaIngresos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbCategoriaIngresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCategoriaIngresosActionPerformed(evt);
            }
        });

        cbCuentaIngresos.setBackground(new java.awt.Color(204, 204, 204));
        cbCuentaIngresos.setEditable(true);
        cbCuentaIngresos.setForeground(new java.awt.Color(0, 0, 0));
        cbCuentaIngresos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtIVA.setBackground(new java.awt.Color(204, 204, 204));
        txtIVA.setForeground(new java.awt.Color(0, 0, 0));
        txtIVA.setText("jTextField1");

        txtConcepto.setBackground(new java.awt.Color(204, 204, 204));
        txtConcepto.setForeground(new java.awt.Color(0, 0, 0));
        txtConcepto.setText("jTextField3");

        dtFecha.setBackground(new java.awt.Color(204, 204, 204));
        dtFecha.setForeground(new java.awt.Color(0, 0, 0));
        dtFecha.setName("dtFecha"); // NOI18N

        txtNumFactura.setBackground(new java.awt.Color(204, 204, 204));
        txtNumFactura.setForeground(new java.awt.Color(0, 0, 0));
        txtNumFactura.setText("jTextField1");

        txtMontoTotal.setBackground(new java.awt.Color(204, 204, 204));
        txtMontoTotal.setForeground(new java.awt.Color(0, 0, 0));
        txtMontoTotal.setText("jTextField1");

        txtMontoNoIVA.setBackground(new java.awt.Color(204, 204, 204));
        txtMontoNoIVA.setForeground(new java.awt.Color(0, 0, 0));
        txtMontoNoIVA.setText("jTextField2");
        txtMontoNoIVA.setEnabled(false);

        txtMontoIVA.setBackground(new java.awt.Color(204, 204, 204));
        txtMontoIVA.setForeground(new java.awt.Color(0, 0, 0));
        txtMontoIVA.setText("jTextField3");

        txtConcepto1.setBackground(new java.awt.Color(204, 204, 204));
        txtConcepto1.setForeground(new java.awt.Color(0, 0, 0));
        txtConcepto1.setText("jTextField3");
        txtConcepto1.setEnabled(false);

        btnGuardar.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        btnGuardar.setText("Guardar");

        javax.swing.GroupLayout pnlIngresosLayout = new javax.swing.GroupLayout(pnlIngresos);
        pnlIngresos.setLayout(pnlIngresosLayout);
        pnlIngresosLayout.setHorizontalGroup(
            pnlIngresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIngresosLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(pnlIngresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(pnlIngresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlIngresosLayout.createSequentialGroup()
                        .addGroup(pnlIngresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtConcepto1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbCuentaIngresos, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbCategoriaIngresos, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIVA, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMontoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMontoNoIVA, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                            .addComponent(txtMontoIVA))
                        .addGap(314, 314, Short.MAX_VALUE))
                    .addGroup(pnlIngresosLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(rdFacturaYes)
                        .addGap(18, 18, 18)
                        .addComponent(rdFacturaNo)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(pnlIngresosLayout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlIngresosLayout.setVerticalGroup(
            pnlIngresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIngresosLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnlIngresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlIngresosLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11))
                    .addGroup(pnlIngresosLayout.createSequentialGroup()
                        .addComponent(dtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbCategoriaIngresos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtConcepto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbCuentaIngresos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtConcepto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnlIngresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdFacturaNo)
                            .addComponent(rdFacturaYes))
                        .addGap(18, 18, 18)
                        .addComponent(txtNumFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(txtMontoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtMontoNoIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtMontoIVA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(249, Short.MAX_VALUE))
        );

        pnlEgresos.setBackground(new java.awt.Color(47, 51, 66));
        pnlEgresos.setName(""); // NOI18N
        pnlEgresos.setPreferredSize(new java.awt.Dimension(837, 722));

        jLabel13.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Fecha");

        jLabel14.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Categoría");

        jLabel15.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Concepto");

        jLabel16.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Cuenta");

        jLabel17.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Forma de pago");

        jLabel18.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("IVA");

        rdFacturaYes1.setBackground(new java.awt.Color(204, 204, 204));
        rdFacturaYes1.setForeground(new java.awt.Color(0, 0, 0));
        rdFacturaYes1.setText("Sí");
        rdFacturaYes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdFacturaYes1ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Factura");

        rdFacturaNo1.setBackground(new java.awt.Color(204, 204, 204));
        rdFacturaNo1.setForeground(new java.awt.Color(0, 0, 0));
        rdFacturaNo1.setText("No");

        jLabel20.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Num. factura");

        jLabel21.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Monto total");

        jLabel22.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Monto sin IVA");

        jLabel23.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Monto IVA");

        cbCategoriaEgresos.setBackground(new java.awt.Color(204, 204, 204));
        cbCategoriaEgresos.setEditable(true);
        cbCategoriaEgresos.setForeground(new java.awt.Color(0, 0, 0));
        cbCategoriaEgresos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbCategoriaEgresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCategoriaEgresosActionPerformed(evt);
            }
        });

        cbCuentaEgresos.setBackground(new java.awt.Color(204, 204, 204));
        cbCuentaEgresos.setEditable(true);
        cbCuentaEgresos.setForeground(new java.awt.Color(0, 0, 0));
        cbCuentaEgresos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtIVA1.setBackground(new java.awt.Color(204, 204, 204));
        txtIVA1.setForeground(new java.awt.Color(0, 0, 0));
        txtIVA1.setText("jTextField1");

        txtConcepto2.setBackground(new java.awt.Color(204, 204, 204));
        txtConcepto2.setForeground(new java.awt.Color(0, 0, 0));
        txtConcepto2.setText("jTextField3");

        dtFecha1.setBackground(new java.awt.Color(204, 204, 204));
        dtFecha1.setForeground(new java.awt.Color(0, 0, 0));
        dtFecha1.setName("dtFecha"); // NOI18N

        txtNumFactura1.setBackground(new java.awt.Color(204, 204, 204));
        txtNumFactura1.setForeground(new java.awt.Color(0, 0, 0));
        txtNumFactura1.setText("jTextField1");

        txtMontoTotal1.setBackground(new java.awt.Color(204, 204, 204));
        txtMontoTotal1.setForeground(new java.awt.Color(0, 0, 0));
        txtMontoTotal1.setText("jTextField1");

        txtMontoNoIVA1.setBackground(new java.awt.Color(204, 204, 204));
        txtMontoNoIVA1.setForeground(new java.awt.Color(0, 0, 0));
        txtMontoNoIVA1.setText("jTextField2");
        txtMontoNoIVA1.setEnabled(false);

        txtMontoIVA1.setBackground(new java.awt.Color(204, 204, 204));
        txtMontoIVA1.setForeground(new java.awt.Color(0, 0, 0));
        txtMontoIVA1.setText("jTextField3");

        txtConcepto3.setBackground(new java.awt.Color(204, 204, 204));
        txtConcepto3.setForeground(new java.awt.Color(0, 0, 0));
        txtConcepto3.setText("jTextField3");
        txtConcepto3.setEnabled(false);

        btnGuardar2.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        btnGuardar2.setText("Guardar");

        javax.swing.GroupLayout pnlEgresosLayout = new javax.swing.GroupLayout(pnlEgresos);
        pnlEgresos.setLayout(pnlEgresosLayout);
        pnlEgresosLayout.setHorizontalGroup(
            pnlEgresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEgresosLayout.createSequentialGroup()
                .addGroup(pnlEgresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEgresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pnlEgresosLayout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addGap(24, 24, 24)
                            .addComponent(dtFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlEgresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEgresosLayout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(cbCuentaEgresos, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlEgresosLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(282, 282, 282)))
                        .addGroup(pnlEgresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlEgresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(pnlEgresosLayout.createSequentialGroup()
                                    .addComponent(jLabel20)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtNumFactura1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlEgresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlEgresosLayout.createSequentialGroup()
                                        .addGap(78, 78, 78)
                                        .addComponent(jLabel18)
                                        .addGap(41, 41, 41)
                                        .addComponent(txtIVA1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlEgresosLayout.createSequentialGroup()
                                        .addGap(59, 59, 59)
                                        .addComponent(jLabel19)
                                        .addGap(23, 23, 23)
                                        .addComponent(rdFacturaYes1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rdFacturaNo1)))
                                .addGroup(pnlEgresosLayout.createSequentialGroup()
                                    .addGroup(pnlEgresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel21)
                                        .addComponent(jLabel23)
                                        .addComponent(jLabel22))
                                    .addGap(18, 18, 18)
                                    .addGroup(pnlEgresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtMontoNoIVA1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtMontoIVA1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtMontoTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(pnlEgresosLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnlEgresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEgresosLayout.createSequentialGroup()
                                        .addGap(142, 142, 142)
                                        .addComponent(txtConcepto3, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlEgresosLayout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addGap(282, 282, 282)))))
                        .addGroup(pnlEgresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlEgresosLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(cbCategoriaEgresos, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlEgresosLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(txtConcepto2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlEgresosLayout.createSequentialGroup()
                        .addGap(438, 438, 438)
                        .addComponent(btnGuardar2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(475, Short.MAX_VALUE))
        );
        pnlEgresosLayout.setVerticalGroup(
            pnlEgresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEgresosLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pnlEgresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dtFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(pnlEgresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cbCategoriaEgresos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlEgresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtConcepto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlEgresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(cbCuentaEgresos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlEgresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtConcepto3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlEgresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(rdFacturaYes1)
                    .addComponent(rdFacturaNo1))
                .addGap(18, 18, 18)
                .addGroup(pnlEgresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtNumFactura1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlEgresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtIVA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(pnlEgresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtMontoTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlEgresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtMontoNoIVA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlEgresosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtMontoIVA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(btnGuardar2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(230, Short.MAX_VALUE))
        );

        pnlMovCaja.setBackground(new java.awt.Color(47, 51, 66));

        jLabel25.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        jLabel25.setText("Fecha");

        jLabel36.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        jLabel36.setText("Caja de salida");

        jLabel38.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        jLabel38.setText("Caja de entrada");

        jLabel39.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        jLabel39.setText("Monto total");

        cbCategoriaEgresos1.setEditable(true);
        cbCategoriaEgresos1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbCategoriaEgresos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCategoriaEgresos1ActionPerformed(evt);
            }
        });

        cbCuentaEgresos1.setEditable(true);
        cbCuentaEgresos1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        dtFecha2.setName("dtFecha"); // NOI18N

        txtConcepto5.setText("jTextField3");
        txtConcepto5.setEnabled(false);

        btnGuardar3.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        btnGuardar3.setText("Guardar");

        cbCuentaEgresos2.setEditable(true);
        cbCuentaEgresos2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel63.setFont(new java.awt.Font("Malgun Gothic", 1, 16)); // NOI18N
        jLabel63.setText("Concepto");

        javax.swing.GroupLayout pnlMovCajaLayout = new javax.swing.GroupLayout(pnlMovCaja);
        pnlMovCaja.setLayout(pnlMovCajaLayout);
        pnlMovCajaLayout.setHorizontalGroup(
            pnlMovCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMovCajaLayout.createSequentialGroup()
                .addGroup(pnlMovCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMovCajaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlMovCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlMovCajaLayout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addGap(24, 24, 24)
                                .addComponent(dtFecha2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlMovCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMovCajaLayout.createSequentialGroup()
                                    .addGap(142, 142, 142)
                                    .addComponent(txtConcepto5, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlMovCajaLayout.createSequentialGroup()
                                    .addComponent(jLabel39)
                                    .addGap(282, 282, 282)))
                            .addGroup(pnlMovCajaLayout.createSequentialGroup()
                                .addComponent(jLabel36)
                                .addGap(18, 18, 18)
                                .addComponent(cbCategoriaEgresos1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlMovCajaLayout.createSequentialGroup()
                        .addGap(436, 436, 436)
                        .addComponent(btnGuardar3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMovCajaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlMovCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlMovCajaLayout.createSequentialGroup()
                                .addComponent(jLabel63)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbCuentaEgresos2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlMovCajaLayout.createSequentialGroup()
                                .addComponent(jLabel38)
                                .addGap(18, 18, 18)
                                .addComponent(cbCuentaEgresos1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(220, Short.MAX_VALUE))
        );
        pnlMovCajaLayout.setVerticalGroup(
            pnlMovCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMovCajaLayout.createSequentialGroup()
                .addContainerGap(239, Short.MAX_VALUE)
                .addGroup(pnlMovCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dtFecha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(pnlMovCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(cbCategoriaEgresos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlMovCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(cbCuentaEgresos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(pnlMovCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel63)
                    .addComponent(cbCuentaEgresos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlMovCajaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(txtConcepto5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(337, 337, 337)
                .addComponent(btnGuardar3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlMenuSuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlIngresos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlEgresos, javax.swing.GroupLayout.DEFAULT_SIZE, 836, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlMovCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(PnlMenuSuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlIngresos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                    .addGap(0, 120, Short.MAX_VALUE)
                    .addComponent(pnlEgresos, javax.swing.GroupLayout.PREFERRED_SIZE, 853, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                    .addGap(0, 121, Short.MAX_VALUE)
                    .addComponent(pnlMovCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout pnlMovimientosLayout = new javax.swing.GroupLayout(pnlMovimientos);
        pnlMovimientos.setLayout(pnlMovimientosLayout);
        pnlMovimientosLayout.setHorizontalGroup(
            pnlMovimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlMovimientosLayout.setVerticalGroup(
            pnlMovimientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlReportes.setBackground(new java.awt.Color(47, 51, 66));

        javax.swing.GroupLayout pnlReportesLayout = new javax.swing.GroupLayout(pnlReportes);
        pnlReportes.setLayout(pnlReportesLayout);
        pnlReportesLayout.setHorizontalGroup(
            pnlReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1056, Short.MAX_VALUE)
        );
        pnlReportesLayout.setVerticalGroup(
            pnlReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 973, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlOpcionesInterfazLayout = new javax.swing.GroupLayout(pnlOpcionesInterfaz);
        pnlOpcionesInterfaz.setLayout(pnlOpcionesInterfazLayout);
        pnlOpcionesInterfazLayout.setHorizontalGroup(
            pnlOpcionesInterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1068, Short.MAX_VALUE)
            .addGroup(pnlOpcionesInterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlOpcionesInterfazLayout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(pnlVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(12, 12, 12)))
            .addGroup(pnlOpcionesInterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlOpcionesInterfazLayout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addComponent(pnlDesarrollo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(9, 9, 9)))
            .addGroup(pnlOpcionesInterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOpcionesInterfazLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlMovimientos, javax.swing.GroupLayout.DEFAULT_SIZE, 836, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(pnlOpcionesInterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlOpcionesInterfazLayout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(pnlReportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(12, 12, 12)))
        );
        pnlOpcionesInterfazLayout.setVerticalGroup(
            pnlOpcionesInterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 985, Short.MAX_VALUE)
            .addGroup(pnlOpcionesInterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlOpcionesInterfazLayout.createSequentialGroup()
                    .addGap(69, 69, 69)
                    .addComponent(pnlVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 738, Short.MAX_VALUE)
                    .addGap(70, 70, 70)))
            .addGroup(pnlOpcionesInterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlOpcionesInterfazLayout.createSequentialGroup()
                    .addGap(9, 9, 9)
                    .addComponent(pnlDesarrollo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(9, 9, 9)))
            .addGroup(pnlOpcionesInterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlOpcionesInterfazLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlMovimientos, javax.swing.GroupLayout.DEFAULT_SIZE, 853, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(pnlOpcionesInterfazLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlOpcionesInterfazLayout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(pnlReportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(12, 12, 12)))
        );

        javax.swing.GroupLayout pnlViewLayout = new javax.swing.GroupLayout(pnlView);
        pnlView.setLayout(pnlViewLayout);
        pnlViewLayout.setHorizontalGroup(
            pnlViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(pnlViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlViewLayout.createSequentialGroup()
                    .addComponent(pnlMenuLateral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(pnlOpcionesInterfaz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnlViewLayout.setVerticalGroup(
            pnlViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(pnlViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnlMenuLateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlOpcionesInterfaz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlViewMainLayout = new javax.swing.GroupLayout(pnlViewMain);
        pnlViewMain.setLayout(pnlViewMainLayout);
        pnlViewMainLayout.setHorizontalGroup(
            pnlViewMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlView, javax.swing.GroupLayout.PREFERRED_SIZE, 966, Short.MAX_VALUE)
        );
        pnlViewMainLayout.setVerticalGroup(
            pnlViewMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlViewMainLayout.createSequentialGroup()
                .addComponent(pnlView, javax.swing.GroupLayout.PREFERRED_SIZE, 660, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        jMenu1.setText("Archivo");

        tlbrNuevoDesarrollo.setText("Nuevo desarrollo");
        tlbrNuevoDesarrollo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tlbrNuevoDesarrolloActionPerformed(evt);
            }
        });
        jMenu1.add(tlbrNuevoDesarrollo);

        tlbrCargarDesarrollo.setText("Cargar desarrollo");
        tlbrCargarDesarrollo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tlbrCargarDesarrolloActionPerformed(evt);
            }
        });
        jMenu1.add(tlbrCargarDesarrollo);

        tlbrAdministración.setText("Administración");
        tlbrAdministración.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tlbrAdministraciónActionPerformed(evt);
            }
        });
        jMenu1.add(tlbrAdministración);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlViewMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlViewMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tlbrNuevoDesarrolloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tlbrNuevoDesarrolloActionPerformed
              NuevoDesarrollo rm = new NuevoDesarrollo();
              rm.setVisible(true);
    }//GEN-LAST:event_tlbrNuevoDesarrolloActionPerformed

    private void tlbrAdministraciónActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tlbrAdministraciónActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tlbrAdministraciónActionPerformed

    private void btnDesarrolloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesarrolloActionPerformed
        // TODO add your handling code here:
        pnlDesarrollo.setVisible(true);
        pnlVentas.setVisible(false);//movimientos reportes
        pnlMovimientos.setVisible(false);
        pnlReportes.setVisible(false);

    }//GEN-LAST:event_btnDesarrolloActionPerformed

    private void btnVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentaActionPerformed
        // TODO add your handling code here:
        pnlVentas.setVisible(true);
        pnlDesarrollo.setVisible(false);
        pnlMovimientos.setVisible(false);
        pnlReportes.setVisible(false);

    }//GEN-LAST:event_btnVentaActionPerformed

    private void btnMovimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovimientosActionPerformed
        // TODO add your handling code here:
        
        pnlDesarrollo.setVisible(false);
        pnlVentas.setVisible(false);//movimientos reportes
        pnlReportes.setVisible(false);
        
        pnlEgresos.setVisible(false);
        pnlIngresos.setVisible(false);
        pnlMovCaja.setVisible(false);

        pnlMovimientos.setVisible(true);
    }//GEN-LAST:event_btnMovimientosActionPerformed

    private void RbtnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbtnReportesActionPerformed
        // TODO add your handling code here:
        pnlReportes.setVisible(true);
        pnlDesarrollo.setVisible(false);
        pnlVentas.setVisible(false);//movimientos reportes
        pnlMovimientos.setVisible(false);
    }//GEN-LAST:event_RbtnReportesActionPerformed

    private void rdFacturaYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdFacturaYesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdFacturaYesActionPerformed

    private void cbCategoriaIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCategoriaIngresosActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cbCategoriaIngresosActionPerformed

    private void rdFacturaYes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdFacturaYes1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdFacturaYes1ActionPerformed

    private void cbCategoriaEgresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCategoriaEgresosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCategoriaEgresosActionPerformed

    private void tlbrCargarDesarrolloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tlbrCargarDesarrolloActionPerformed
        // TODO add your handling code here:
        pnlOpcionesInterfaz.setVisible(true);
        pnlMenuLateral.setVisible(true);
    }//GEN-LAST:event_tlbrCargarDesarrolloActionPerformed

    private void btnIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresosActionPerformed
        // TODO add your handling code here:
        pnlIngresos.setVisible(true);
        pnlEgresos.setVisible(false);
        pnlMovCaja.setVisible(false);
    }//GEN-LAST:event_btnIngresosActionPerformed

    private void btnMovCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMovCajaActionPerformed
        // TODO add your handling code here:
        pnlMovCaja.setVisible(true);
        pnlIngresos.setVisible(false);
        pnlEgresos.setVisible(false);
    }//GEN-LAST:event_btnMovCajaActionPerformed

    private void btnEgresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEgresosActionPerformed
        // TODO add your handling code here:
        pnlIngresos.setVisible(false);
        pnlEgresos.setVisible(true);
        pnlMovCaja.setVisible(false);
    }//GEN-LAST:event_btnEgresosActionPerformed

    private void cbCategoriaEgresos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCategoriaEgresos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCategoriaEgresos1ActionPerformed

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        // TODO add your handling code here:
        if(pnlIngresos.isVisible()){
            RegistroIngresos ri = new RegistroIngresos();
            ri.setVisible(true);
        }else if (pnlEgresos.isVisible()){
            RegistroEgresos re = new RegistroEgresos();
            re.setVisible(true);
        }else if(pnlMovCaja.isVisible()){
            RegistroMovimientos rm = new RegistroMovimientos();
            rm.setVisible(true);
        }
    }//GEN-LAST:event_btnRegistroActionPerformed

    private void btnEditProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditProjectActionPerformed
  NuevoDesarrollo rm = new NuevoDesarrollo();
              rm.setVisible(true);
              // TODO add your handling code here:
    }//GEN-LAST:event_btnEditProjectActionPerformed

    private void tableVentasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableVentasMouseReleased
          if (evt.getClickCount() == 2 && !evt.isConsumed()) {
        evt.consume();
        menuVentasDisponibles.show(tableVentas, evt.getX(), evt.getY());
        }    
    }//GEN-LAST:event_tableVentasMouseReleased

    private void btnVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderActionPerformed
         VentaUnidades rm = new VentaUnidades();
         rm.setModal(true);
            rm.setVisible(true);
    }//GEN-LAST:event_btnVenderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlMenuSuperior;
    private javax.swing.JPanel PnlMenuSuperior1;
    private javax.swing.JButton RbtnReportes;
    private javax.swing.JButton btnAddPlanPago;
    private javax.swing.JMenuItem btnAgregar;
    private javax.swing.JButton btnDesarrollo;
    private javax.swing.JMenuItem btnDevaluacion;
    private javax.swing.JButton btnEditProject;
    private javax.swing.JButton btnEgresos;
    private javax.swing.JMenuItem btnGenerarEstadoContrato;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnGuardar2;
    private javax.swing.JButton btnGuardar3;
    private javax.swing.JMenuItem btnInfoVenta;
    private javax.swing.JButton btnIngresos;
    private javax.swing.JButton btnMovCaja;
    private javax.swing.JButton btnMovimientos;
    private javax.swing.JMenuItem btnPagos;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JMenuItem btnVender;
    private javax.swing.JButton btnVenta;
    private javax.swing.JComboBox<String> cbCategoriaEgresos;
    private javax.swing.JComboBox<String> cbCategoriaEgresos1;
    private javax.swing.JComboBox<String> cbCategoriaIngresos;
    private javax.swing.JComboBox<String> cbCuentaEgresos;
    private javax.swing.JComboBox<String> cbCuentaEgresos1;
    private javax.swing.JComboBox<String> cbCuentaEgresos2;
    private javax.swing.JComboBox<String> cbCuentaIngresos;
    private com.toedter.calendar.JDateChooser dtFecha;
    private com.toedter.calendar.JDateChooser dtFecha1;
    private com.toedter.calendar.JDateChooser dtFecha2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPopupMenu menuVentasDisponibles;
    private javax.swing.JPopupMenu menuVentasNoDisponibles;
    private javax.swing.JPanel pnlDesarrollo;
    private javax.swing.JPanel pnlEgresos;
    private javax.swing.JPanel pnlIngresos;
    private javax.swing.JPanel pnlMenuLateral;
    private javax.swing.JPanel pnlMenuLateral1;
    private javax.swing.JPanel pnlMovCaja;
    private javax.swing.JPanel pnlMovimientos;
    private javax.swing.JPanel pnlOpcionesInterfaz;
    private javax.swing.JPanel pnlReportes;
    private javax.swing.JPanel pnlVentas;
    private javax.swing.JPanel pnlView;
    private javax.swing.JPanel pnlViewMain;
    private javax.swing.JRadioButton rdFacturaNo;
    private javax.swing.JRadioButton rdFacturaNo1;
    private javax.swing.JRadioButton rdFacturaYes;
    private javax.swing.JRadioButton rdFacturaYes1;
    private javax.swing.JTable tableVentas;
    private javax.swing.JMenuItem tlbrAdministración;
    private javax.swing.JMenuItem tlbrCargarDesarrollo;
    private javax.swing.JMenuItem tlbrNuevoDesarrollo;
    private javax.swing.JTextField txtConcepto;
    private javax.swing.JTextField txtConcepto1;
    private javax.swing.JTextField txtConcepto2;
    private javax.swing.JTextField txtConcepto3;
    private javax.swing.JTextField txtConcepto5;
    private javax.swing.JTextField txtIVA;
    private javax.swing.JTextField txtIVA1;
    private javax.swing.JTextField txtMontoIVA;
    private javax.swing.JTextField txtMontoIVA1;
    private javax.swing.JTextField txtMontoNoIVA;
    private javax.swing.JTextField txtMontoNoIVA1;
    private javax.swing.JTextField txtMontoTotal;
    private javax.swing.JTextField txtMontoTotal1;
    private javax.swing.JTextField txtNumFactura;
    private javax.swing.JTextField txtNumFactura1;
    // End of variables declaration//GEN-END:variables
}
