/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package devso2;
//import Adicional.ExportExc;
import Classes.Expense;
import Classes.Income;
import Classes.Provider;
import Classes.Save;
import Conexion.Conexion;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.*;
import java.io.IOException;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.*;
/**
 *
 * @author macbook
 */
public class RegistroEgresos extends javax.swing.JDialog {

    /**
     * Creates new form RegistroEgresos
     */
    public RegistroEgresos() {
        initComponents();
        setIconImage (new ImageIcon(getClass().getResource("Images/Screenshot_1.png")).getImage());
       ImageIcon imagen1 = new ImageIcon(getClass().getResource("Images/Eliminar.png"));
        Icon fondo1 = new ImageIcon(imagen1.getImage().getScaledInstance(25, 25, Image.SCALE_SMOOTH));
        btnEliminar.setIcon(fondo1);
          ImageIcon imagen4 = new ImageIcon(getClass().getResource("Images/Buscar.png"));
        Icon fondo4 = new ImageIcon(imagen4.getImage().getScaledInstance(25, 25, Image.SCALE_SMOOTH));
        txtBuscar.setIcon(fondo4);
        tableEgresos.getTableHeader().setBackground(Color.white);
        tableEgresos.getTableHeader().setForeground(Color.black);
        tableEgresos.getTableHeader().setFont(new Font("InaiMathi", 0, 20)); 
        tableEgresos.getColumnModel().getColumn(8).setCellRenderer(new CurrencyCellRenderer());
          tableEgresos.getColumnModel().getColumn(9).setCellRenderer(new CurrencyCellRenderer());
              tableEgresos.getColumnModel().getColumn(7).setCellRenderer(new CurrencyCellRenderer());
              DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
        tableEgresos.getColumnModel().getColumn(0).setCellRenderer(tcr);
             tableEgresos.getColumnModel().getColumn(1).setCellRenderer(new TimestampCellRenderer());
        tableEgresos.getColumnModel().getColumn(2).setCellRenderer(tcr);
        tableEgresos.getColumnModel().getColumn(3).setCellRenderer(tcr);
        tableEgresos.getColumnModel().getColumn(4).setCellRenderer(tcr); 
        tableEgresos.getColumnModel().getColumn(6).setCellRenderer(tcr);

        con=new Conexion();
        model=(DefaultTableModel)tableEgresos.getModel();
        con.Conectar();        
     try{
     if(Save.ingreso ==1){
         expenses=con.GetExpensesByProvider(Save.Provider);
         prov=con.GetProviderById(Save.Provider);
         jLabel3.setText("Pagos de "+prov.Description);
         this.setTitle("Pagos de "+prov.Description);
       DecimalFormat formatea = new DecimalFormat("$###,###.##");    
           txtSaldo.setText(formatea.format(prov.Saldo()));

     }else{
         lblSaldo.setVisible(false);
         txtSaldo.setVisible(false);
         jScrollPane7.setVisible(false);
         btnAgregarPago.setVisible(false);
          expenses=con.GetExpenses();
     }
      } catch (SQLException ex) {
                 }
     con.Desconectar();
        for(Expense obj: expenses)
        {
            //model.addRow(new Object[]{obj.Id,obj.Date,obj.Expense_Type,obj.Concept,obj.Account,
            //obj.Bill(),obj.BillsNumber,obj.Amount,obj.Iva(),obj.AmountSinIva()});
        }
              trs=new TableRowSorter(model);
        tableEgresos.setRowSorter(trs);
    }
  private DefaultTableModel model;
    public List<Expense> expenses; 
    public Provider prov;
     Conexion con;
     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SubMenu = new javax.swing.JPopupMenu();
        btnEliminar = new javax.swing.JMenuItem();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableEgresos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtBusqueda = new javax.swing.JTextPane();
        txtBuscar = new javax.swing.JLabel();
        cbxFiltro = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnAgregarPago = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtSaldo = new javax.swing.JTextPane();
        lblSaldo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        SubMenu.add(btnEliminar);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registro de egresos");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(47, 51, 66));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel3MouseReleased(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("InaiMathi", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Registro de egresos");

        tableEgresos.setBackground(new java.awt.Color(204, 204, 204));
        tableEgresos.setFont(new java.awt.Font("InaiMathi", 0, 18)); // NOI18N
        tableEgresos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Fecha", "Categoría", "Detalle", "Cuenta", "Factura", "No. de Factura", "Monto Total", "Iva", "Monto Sin Iva"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Object.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableEgresos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tableEgresos.setFocusTraversalPolicyProvider(true);
        tableEgresos.setGridColor(new java.awt.Color(153, 153, 153));
        tableEgresos.setMinimumSize(new java.awt.Dimension(2147483647, 2147483647));
        tableEgresos.setRowHeight(22);
        tableEgresos.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tableEgresos.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tableEgresos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tableEgresosMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tableEgresos);

        txtBusqueda.setBackground(new java.awt.Color(255, 255, 255));
        txtBusqueda.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        txtBusqueda.setFont(new java.awt.Font("InaiMathi", 0, 14)); // NOI18N
        txtBusqueda.setForeground(new java.awt.Color(51, 51, 51));
        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyTyped(evt);
            }
        });
        jScrollPane2.setViewportView(txtBusqueda);

        txtBuscar.setFont(new java.awt.Font("InaiMathi", 0, 14)); // NOI18N
        txtBuscar.setForeground(new java.awt.Color(255, 255, 255));
        txtBuscar.setText("Buscar:");

        cbxFiltro.setBackground(new java.awt.Color(255, 255, 255));
        cbxFiltro.setFont(new java.awt.Font("InaiMathi", 0, 14)); // NOI18N
        cbxFiltro.setForeground(new java.awt.Color(51, 51, 51));
        cbxFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Id", "Fecha", "Categoría", "Detalle", "Tipo de pago", "Cuenta", "Factura", "No. de Factura", "Monto Total", "Iva", "Monto sin iva" }));

        jLabel2.setFont(new java.awt.Font("InaiMathi", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("En:");

        btnAgregarPago.setBackground(new java.awt.Color(217, 234, 220));
        btnAgregarPago.setFont(new java.awt.Font("InaiMathi", 0, 12)); // NOI18N
        btnAgregarPago.setForeground(new java.awt.Color(51, 51, 51));
        btnAgregarPago.setText("Agregar nuevo pago");
        btnAgregarPago.setToolTipText("");
        btnAgregarPago.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(145, 146, 147)));
        btnAgregarPago.setFocusTraversalPolicyProvider(true);
        btnAgregarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPagoActionPerformed(evt);
            }
        });

        txtSaldo.setEditable(false);
        txtSaldo.setBackground(new java.awt.Color(255, 255, 255));
        txtSaldo.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        txtSaldo.setFont(new java.awt.Font("InaiMathi", 0, 16)); // NOI18N
        txtSaldo.setForeground(new java.awt.Color(51, 51, 51));
        txtSaldo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSaldoKeyTyped(evt);
            }
        });
        jScrollPane7.setViewportView(txtSaldo);

        lblSaldo.setFont(new java.awt.Font("InaiMathi", 0, 14)); // NOI18N
        lblSaldo.setForeground(new java.awt.Color(255, 255, 255));
        lblSaldo.setText("Saldo:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(lblSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(btnAgregarPago, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(btnAgregarPago, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 204));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jMenu2.setBackground(new java.awt.Color(204, 204, 204));
        jMenu2.setForeground(new java.awt.Color(51, 51, 51));
        jMenu2.setText("Exportar");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setBackground(new java.awt.Color(255, 248, 245));
        jMenuItem3.setForeground(new java.awt.Color(51, 51, 51));
        jMenuItem3.setText("Archivo de Excel");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  TableRowSorter trs;
    private void txtBusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyTyped
  txtBusqueda.addKeyListener(new KeyAdapter(){       
           @Override
           public void keyReleased(KeyEvent ke){
           trs.setRowFilter(RowFilter.regexFilter("(?i)"+txtBusqueda.getText(),cbxFiltro.getSelectedIndex()));
           }
           });
         trs=new TableRowSorter(model);  
         tableEgresos.setRowSorter(trs);

    }//GEN-LAST:event_txtBusquedaKeyTyped

    private void jPanel3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseReleased

    }//GEN-LAST:event_jPanel3MouseReleased

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
   
        int n = JOptionPane.showConfirmDialog(this,
            "¿Desea eliminar el registro "+ tableEgresos.getValueAt(tableEgresos.getSelectedRow(), 0).toString() +"?","Confirmación",
            JOptionPane.YES_NO_OPTION);
        if(n==JOptionPane.YES_OPTION){

            con=new Conexion();
            con.Conectar();
            try{
                con.DeleteExpense(Integer.parseInt( tableEgresos.getValueAt(tableEgresos.getSelectedRow(), 0).toString()));
                 if(Save.ingreso ==1){
        prov=con.GetProviderById(Save.Provider);
        DecimalFormat formatea = new DecimalFormat("$###,###.##");    
        txtSaldo.setText(formatea.format(prov.Saldo()));
        expenses=con.GetExpensesByProvider(Save.Provider);
     }else{
          expenses=con.GetExpenses();
     }
            } catch (SQLException ex) {
            }
            con.Desconectar();
            JOptionPane.showMessageDialog(this,"Egreso eliminado con éxito.");

            int j=model.getRowCount();
            for(int i=0;i<j;i++){
                model.removeRow(j-i-1);
            }
                   for(Expense obj: expenses)
        {
            //model.addRow(new Object[]{obj.Id,obj.Date,obj.Expense_Type,obj.Concept,obj.Account,
            //obj.Bill(),obj.BillsNumber,obj.Amount,obj.Iva(),obj.AmountSinIva()});
        }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tableEgresosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableEgresosMouseReleased
 if (evt.getClickCount() == 2 && !evt.isConsumed()) {
        evt.consume();
        SubMenu.show(tableEgresos, evt.getX(), evt.getY());
        }         
    }//GEN-LAST:event_tableEgresosMouseReleased

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        //Interfaz.RegistroEgresosBool=false;
    }//GEN-LAST:event_formWindowClosing

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
//        ExportExc j=new ExportExc();
//        try{
//            j.exportarExcel(tableEgresos);}
//        catch(IOException e){}
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void btnAgregarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPagoActionPerformed
        Save.ingreso=1;
//        try{
// 
//            Save.Providertext=prov.Description;
//            Save.ProviderSaldo=prov.Saldo();
//            AuxPagos form=new AuxPagos();
//            form.setModal(true);
//            form.setVisible(true);
//      }catch(Exception e){}
       int j=model.getRowCount();
        for(int i=0;i<j;i++){
            model.removeRow(j-i-1);
        }
        
        con=new Conexion();
        con.Conectar();
        try{
            expenses=con.GetExpensesByProvider(Save.Provider);
         prov=con.GetProviderById(Save.Provider);
       DecimalFormat formatea = new DecimalFormat("$###,###.##");    
           txtSaldo.setText(formatea.format(prov.Saldo()));
        } catch (SQLException ex) {
        }
        con.Desconectar();
        
       for(Expense obj: expenses)
        {
            //model.addRow(new Object[]{obj.Id,obj.Date,obj.Expense_Type,obj.Concept,obj.Account,
            //obj.Bill(),obj.BillsNumber,obj.Amount,obj.Iva(),obj.AmountSinIva()});
        }
    }//GEN-LAST:event_btnAgregarPagoActionPerformed

    private void txtSaldoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSaldoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSaldoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroEgresos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroEgresos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroEgresos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroEgresos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroEgresos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu SubMenu;
    private javax.swing.JButton btnAgregarPago;
    private javax.swing.JMenuItem btnEliminar;
    private javax.swing.JComboBox<String> cbxFiltro;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JTable tableEgresos;
    private javax.swing.JLabel txtBuscar;
    private javax.swing.JTextPane txtBusqueda;
    private javax.swing.JTextPane txtSaldo;
    // End of variables declaration//GEN-END:variables
}
