/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package devso2;


//import Adicional.ExportExc;
import Classes.Expense;
import Classes.Income;
import Classes.Moves_Account;
import Classes.Save;
import Conexion.Conexion;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.*;
import java.io.IOException;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.*;
        

/**
 *
 * @author macbook
 */
public class RegistroMovimientos extends javax.swing.JFrame {
    public RegistroMovimientos(){
          initComponents();
         
   setIconImage (new ImageIcon(getClass().getResource("Images/Screenshot_1.png")).getImage());
         
            ImageIcon imagen1 = new ImageIcon(getClass().getResource("Images/Eliminar.png"));
        Icon fondo1 = new ImageIcon(imagen1.getImage().getScaledInstance(25, 25, Image.SCALE_SMOOTH));
        btnEliminar.setIcon(fondo1);
          ImageIcon imagen4 = new ImageIcon(getClass().getResource("Images/Buscar.png"));
        Icon fondo4 = new ImageIcon(imagen4.getImage().getScaledInstance(25, 25, Image.SCALE_SMOOTH));
        txtBuscar.setIcon(fondo4);
        tableEgresos.getTableHeader().setBackground(Color.white);
        tableEgresos.getTableHeader().setForeground(Color.black);
        tableEgresos.getTableHeader().setFont(new Font("InaiMathi", 0, 20)); 
        tableEgresos.getColumnModel().getColumn(5).setCellRenderer(new CurrencyCellRenderer());
        DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
        tableEgresos.getColumnModel().getColumn(0).setCellRenderer(tcr);
        tableEgresos.getColumnModel().getColumn(1).setCellRenderer(new TimestampCellRenderer());
        tableEgresos.getColumnModel().getColumn(2).setCellRenderer(tcr);
        tableEgresos.getColumnModel().getColumn(3).setCellRenderer(tcr);
        tableEgresos.getColumnModel().getColumn(4).setCellRenderer(tcr); 
        con=new Conexion();
             con.Conectar();       
        model=(DefaultTableModel)tableEgresos.getModel();
        try{
         expenses=con.GetMovesCajas();

    
      } catch (SQLException ex) {
                    Logger.getLogger(RegistroIngresos.class.getName()).log(Level.SEVERE, null, ex);
                }
     con.Desconectar();
        for(Moves_Account obj: expenses)
        {
            model.addRow(new Object[]{obj.Id,obj.Date,obj.AccountOut,obj.AccountIn,obj.Description,obj.Amount});
        }
            
              trs=new TableRowSorter(model);
        tableEgresos.setRowSorter(trs);
       tableEgresos.doLayout();
        }
    TableRowSorter trs;
  private DefaultTableModel model;
    public List<Moves_Account> expenses; 
     Conexion con;
    /**
  
    }
 private DefaultTableModel model;
    public List<Movimiento_Cajas> movimientos; 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SubMenu = new javax.swing.JPopupMenu();
        btnEliminar = new javax.swing.JMenuItem();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtBusqueda1 = new javax.swing.JTextPane();
        txtBuscar = new javax.swing.JLabel();
        cbxFiltro1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableEgresos = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        SubMenu.add(btnEliminar);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel4MouseReleased(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("InaiMathi", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Registro de movimiento de cajas");

        txtBusqueda1.setBackground(new java.awt.Color(255, 248, 245));
        txtBusqueda1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        txtBusqueda1.setFont(new java.awt.Font("InaiMathi", 0, 14)); // NOI18N
        txtBusqueda1.setForeground(new java.awt.Color(51, 51, 51));
        txtBusqueda1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBusqueda1KeyTyped(evt);
            }
        });
        jScrollPane6.setViewportView(txtBusqueda1);

        txtBuscar.setFont(new java.awt.Font("InaiMathi", 0, 14)); // NOI18N
        txtBuscar.setForeground(new java.awt.Color(51, 51, 51));
        txtBuscar.setText("Buscar:");

        cbxFiltro1.setBackground(new java.awt.Color(255, 248, 245));
        cbxFiltro1.setFont(new java.awt.Font("InaiMathi", 0, 14)); // NOI18N
        cbxFiltro1.setForeground(new java.awt.Color(51, 51, 51));
        cbxFiltro1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Id", "Fecha", "Cuenta de salida", "Cuenta de entrada", "Detalle", "Monto total" }));

        jLabel8.setFont(new java.awt.Font("InaiMathi", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("En:");

        tableEgresos.setBackground(new java.awt.Color(253, 239, 229));
        tableEgresos.setFont(new java.awt.Font("InaiMathi", 0, 18)); // NOI18N
        tableEgresos.setForeground(new java.awt.Color(0, 0, 0));
        tableEgresos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Fecha", "Cuenta de Salida", "Cuenta de Entrada", "Detalle", "Monto Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableEgresos.setGridColor(new java.awt.Color(153, 153, 153));
        tableEgresos.setRowHeight(22);
        tableEgresos.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tableEgresos.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tableEgresos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tableEgresosMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tableEgresos);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxFiltro1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 214, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxFiltro1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 248, 245));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        jMenu2.setBackground(new java.awt.Color(255, 248, 245));
        jMenu2.setForeground(new java.awt.Color(51, 51, 51));
        jMenu2.setText("Exportar");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setBackground(new java.awt.Color(255, 248, 245));
        jMenuItem3.setForeground(new java.awt.Color(51, 51, 51));
        jMenuItem3.setText("Archivo de Excel");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBusqueda1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusqueda1KeyTyped
        txtBusqueda1.addKeyListener(new KeyAdapter(){
            @Override
            public void keyReleased(KeyEvent ke){
                trs.setRowFilter(RowFilter.regexFilter("(?i)"+txtBusqueda1.getText(),cbxFiltro1.getSelectedIndex()));
            }
        });
        trs=new TableRowSorter(model);
        tableEgresos.setRowSorter(trs);
    }//GEN-LAST:event_txtBusqueda1KeyTyped

    private void jPanel4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseReleased

    }//GEN-LAST:event_jPanel4MouseReleased

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        int n = JOptionPane.showConfirmDialog(this,
            "¿Desea eliminar el registro "+ tableEgresos.getValueAt(tableEgresos.getSelectedRow(), 0).toString() +"?","Confirmación",
            JOptionPane.YES_NO_OPTION);
        if(n==JOptionPane.YES_OPTION){

            con=new Conexion();
            con.Conectar();
            try{
                con.DeleteMov(Integer.parseInt( tableEgresos.getValueAt(tableEgresos.getSelectedRow(), 0).toString()));
                expenses=con.GetMovesCajas();
            } catch (SQLException ex) {
            }
            con.Desconectar();
            JOptionPane.showMessageDialog(this,"Movimiento de caja eliminado con éxito.");

            int j=model.getRowCount();
            for(int i=0;i<j;i++){
                model.removeRow(j-i-1);
            }
              for(Moves_Account obj: expenses)
        {
            model.addRow(new Object[]{obj.Id,obj.Date,obj.AccountOut,obj.AccountIn,obj.Description,obj.Amount});
        }
            
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tableEgresosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableEgresosMouseReleased
   if (evt.getClickCount() == 2 && !evt.isConsumed()) {
        evt.consume();
        SubMenu.show(tableEgresos, evt.getX(), evt.getY());
        }            // TODO add your handling code here:
    }//GEN-LAST:event_tableEgresosMouseReleased

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        //Interfaz.RegistroMovimientosBool=false;
    }//GEN-LAST:event_formWindowClosing

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        //ExportExc j=new ExportExc();
//        try{
//            j.exportarExcel(tableEgresos);}
//        catch(IOException e){}
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroMovimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroMovimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroMovimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroMovimientos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroMovimientos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu SubMenu;
    private javax.swing.JMenuItem btnEliminar;
    private javax.swing.JComboBox<String> cbxFiltro1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable tableEgresos;
    private javax.swing.JLabel txtBuscar;
    private javax.swing.JTextPane txtBusqueda1;
    // End of variables declaration//GEN-END:variables
}
